services:
  nginx:
    hostname: nginx
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
      - phpmyadmin
    networks:
      - frontend
      - backend
      - phpmyadmin
    ports:
      - "80:80"

  frontend:
    hostname: frontend
    image: node:22
    working_dir: /workspace
    container_name: frontend
    volumes:
      - ./frontend/source:/workspace
    command: /bin/sh -c "yarn install && yarn dev"
    tty: true
    expose:
      - '3000'
    networks:
      - frontend
      - backend
    
  backend:
    hostname: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    container_name: backend
    volumes:
      - ./backend/source:/workspace
    tty: true
    expose:
      - '3001'
    networks:
      - backend
      - mysql
    
  mysql:
    image: mysql:8.4
    container_name: mysql
    volumes:
      - mysql_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'yutatravel5'
    expose:
      - '3306'
    networks:
      - mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 2s
      retries: 5
  
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_ABSOLUTE_URI: "http://localhost/phpmyadmin/"
    expose:
      - '80'
    networks:
      - phpmyadmin
      - mysql
  
volumes:
  mysql_db:
  
networks:
  frontend:
  backend:
  mysql:
  phpmyadmin: